# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MainView.ui'
#
# Created: Fri Jul 31 21:59:27 2015
#      by: PyQt4 UI code generator 4.10.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_tabWidget(object):
    def setupUi(self, tabWidget):
        tabWidget.setObjectName(_fromUtf8("tabWidget"))
        tabWidget.resize(1090, 745)
        self.configTab = QtGui.QWidget()
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.configTab.sizePolicy().hasHeightForWidth())
        self.configTab.setSizePolicy(sizePolicy)
        self.configTab.setObjectName(_fromUtf8("configTab"))
        self.gridLayout_2 = QtGui.QGridLayout(self.configTab)
        self.gridLayout_2.setMargin(0)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.splitter_2 = QtGui.QSplitter(self.configTab)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName(_fromUtf8("splitter_2"))
        self.flowchartCtrlWidget = QtGui.QWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.flowchartCtrlWidget.sizePolicy().hasHeightForWidth())
        self.flowchartCtrlWidget.setSizePolicy(sizePolicy)
        self.flowchartCtrlWidget.setObjectName(_fromUtf8("flowchartCtrlWidget"))
        self.verticalLayout_4 = QtGui.QVBoxLayout(self.flowchartCtrlWidget)
        self.verticalLayout_4.setSpacing(0)
        self.verticalLayout_4.setMargin(0)
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.parametersLabel = QtGui.QLabel(self.flowchartCtrlWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parametersLabel.sizePolicy().hasHeightForWidth())
        self.parametersLabel.setSizePolicy(sizePolicy)
        self.parametersLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.parametersLabel.setObjectName(_fromUtf8("parametersLabel"))
        self.verticalLayout_4.addWidget(self.parametersLabel)
        self.widget_4 = QtGui.QWidget(self.flowchartCtrlWidget)
        self.widget_4.setObjectName(_fromUtf8("widget_4"))
        self.verticalLayout_4.addWidget(self.widget_4)
        self.flowchartWidget = QtGui.QWidget(self.splitter_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.flowchartWidget.sizePolicy().hasHeightForWidth())
        self.flowchartWidget.setSizePolicy(sizePolicy)
        self.flowchartWidget.setObjectName(_fromUtf8("flowchartWidget"))
        self.verticalLayout_5 = QtGui.QVBoxLayout(self.flowchartWidget)
        self.verticalLayout_5.setSpacing(0)
        self.verticalLayout_5.setMargin(0)
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.netFlowchartLabel = QtGui.QLabel(self.flowchartWidget)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.netFlowchartLabel.sizePolicy().hasHeightForWidth())
        self.netFlowchartLabel.setSizePolicy(sizePolicy)
        self.netFlowchartLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.netFlowchartLabel.setObjectName(_fromUtf8("netFlowchartLabel"))
        self.verticalLayout_5.addWidget(self.netFlowchartLabel)
        self.widget_5 = QtGui.QWidget(self.flowchartWidget)
        self.widget_5.setObjectName(_fromUtf8("widget_5"))
        self.verticalLayout_5.addWidget(self.widget_5)
        self.gridLayout_2.addWidget(self.splitter_2, 0, 0, 1, 1)
        tabWidget.addTab(self.configTab, _fromUtf8(""))
        self.trainTab = QtGui.QWidget()
        self.trainTab.setObjectName(_fromUtf8("trainTab"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout(self.trainTab)
        self.horizontalLayout_2.setMargin(0)
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.gridLayout = QtGui.QGridLayout()
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.trainParamTree = ParameterTree(self.trainTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.trainParamTree.sizePolicy().hasHeightForWidth())
        self.trainParamTree.setSizePolicy(sizePolicy)
        self.trainParamTree.setRootIsDecorated(True)
        self.trainParamTree.setHeaderHidden(True)
        self.trainParamTree.setObjectName(_fromUtf8("trainParamTree"))
        self.trainParamTree.headerItem().setText(0, _fromUtf8("1"))
        self.gridLayout.addWidget(self.trainParamTree, 0, 0, 2, 1)
        self.trainGraphicsLayout = GraphicsLayoutWidget(self.trainTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(12)
        sizePolicy.setHeightForWidth(self.trainGraphicsLayout.sizePolicy().hasHeightForWidth())
        self.trainGraphicsLayout.setSizePolicy(sizePolicy)
        self.trainGraphicsLayout.setObjectName(_fromUtf8("trainGraphicsLayout"))
        self.gridLayout.addWidget(self.trainGraphicsLayout, 0, 1, 1, 1)
        self.controlBox = QtGui.QGroupBox(self.trainTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.controlBox.sizePolicy().hasHeightForWidth())
        self.controlBox.setSizePolicy(sizePolicy)
        self.controlBox.setAlignment(QtCore.Qt.AlignCenter)
        self.controlBox.setObjectName(_fromUtf8("controlBox"))
        self.horizontalLayout_3 = QtGui.QHBoxLayout(self.controlBox)
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.trainButton = QtGui.QPushButton(self.controlBox)
        self.trainButton.setObjectName(_fromUtf8("trainButton"))
        self.horizontalLayout_3.addWidget(self.trainButton)
        self.stopButton = QtGui.QPushButton(self.controlBox)
        self.stopButton.setObjectName(_fromUtf8("stopButton"))
        self.horizontalLayout_3.addWidget(self.stopButton)
        self.resumeButton = QtGui.QPushButton(self.controlBox)
        self.resumeButton.setObjectName(_fromUtf8("resumeButton"))
        self.horizontalLayout_3.addWidget(self.resumeButton)
        self.gridLayout.addWidget(self.controlBox, 1, 1, 1, 1)
        self.horizontalLayout_2.addLayout(self.gridLayout)
        tabWidget.addTab(self.trainTab, _fromUtf8(""))
        self.testTab = QtGui.QWidget()
        self.testTab.setObjectName(_fromUtf8("testTab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.testTab)
        self.gridLayout_3.setMargin(0)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.splitter = QtGui.QSplitter(self.testTab)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.splitter.sizePolicy().hasHeightForWidth())
        self.splitter.setSizePolicy(sizePolicy)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setChildrenCollapsible(False)
        self.splitter.setObjectName(_fromUtf8("splitter"))
        self.flowchartCtrlWidget_2 = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(1)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.flowchartCtrlWidget_2.sizePolicy().hasHeightForWidth())
        self.flowchartCtrlWidget_2.setSizePolicy(sizePolicy)
        self.flowchartCtrlWidget_2.setObjectName(_fromUtf8("flowchartCtrlWidget_2"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.flowchartCtrlWidget_2)
        self.verticalLayout_3.setSpacing(0)
        self.verticalLayout_3.setMargin(0)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.parametersLabel_2 = QtGui.QLabel(self.flowchartCtrlWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.parametersLabel_2.sizePolicy().hasHeightForWidth())
        self.parametersLabel_2.setSizePolicy(sizePolicy)
        self.parametersLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.parametersLabel_2.setObjectName(_fromUtf8("parametersLabel_2"))
        self.verticalLayout_3.addWidget(self.parametersLabel_2)
        self.widget_3 = QtGui.QWidget(self.flowchartCtrlWidget_2)
        self.widget_3.setObjectName(_fromUtf8("widget_3"))
        self.verticalLayout_3.addWidget(self.widget_3)
        self.flowchartWidget_2 = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(8)
        sizePolicy.setHeightForWidth(self.flowchartWidget_2.sizePolicy().hasHeightForWidth())
        self.flowchartWidget_2.setSizePolicy(sizePolicy)
        self.flowchartWidget_2.setObjectName(_fromUtf8("flowchartWidget_2"))
        self.verticalLayout_2 = QtGui.QVBoxLayout(self.flowchartWidget_2)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setMargin(0)
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.netFlowchartLabel_2 = QtGui.QLabel(self.flowchartWidget_2)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.netFlowchartLabel_2.sizePolicy().hasHeightForWidth())
        self.netFlowchartLabel_2.setSizePolicy(sizePolicy)
        self.netFlowchartLabel_2.setAlignment(QtCore.Qt.AlignCenter)
        self.netFlowchartLabel_2.setObjectName(_fromUtf8("netFlowchartLabel_2"))
        self.verticalLayout_2.addWidget(self.netFlowchartLabel_2)
        self.widget_2 = QtGui.QWidget(self.flowchartWidget_2)
        self.widget_2.setObjectName(_fromUtf8("widget_2"))
        self.verticalLayout_2.addWidget(self.widget_2)
        self.displayLayout = QtGui.QWidget(self.splitter)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.displayLayout.sizePolicy().hasHeightForWidth())
        self.displayLayout.setSizePolicy(sizePolicy)
        self.displayLayout.setMinimumSize(QtCore.QSize(100, 100))
        self.displayLayout.setObjectName(_fromUtf8("displayLayout"))
        self.verticalLayout = QtGui.QVBoxLayout(self.displayLayout)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setMargin(0)
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.displayLabel = QtGui.QLabel(self.displayLayout)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Preferred, QtGui.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.displayLabel.sizePolicy().hasHeightForWidth())
        self.displayLabel.setSizePolicy(sizePolicy)
        self.displayLabel.setAlignment(QtCore.Qt.AlignCenter)
        self.displayLabel.setObjectName(_fromUtf8("displayLabel"))
        self.verticalLayout.addWidget(self.displayLabel)
        self.displayArea = DockArea(self.displayLayout)
        self.displayArea.setObjectName(_fromUtf8("displayArea"))
        self.verticalLayout.addWidget(self.displayArea)
        self.gridLayout_3.addWidget(self.splitter, 0, 0, 1, 1)
        tabWidget.addTab(self.testTab, _fromUtf8(""))

        self.retranslateUi(tabWidget)
        tabWidget.setCurrentIndex(2)
        QtCore.QMetaObject.connectSlotsByName(tabWidget)

    def retranslateUi(self, tabWidget):
        tabWidget.setWindowTitle(_translate("tabWidget", "CaffeViz", None))
        self.parametersLabel.setText(_translate("tabWidget", "Params", None))
        self.netFlowchartLabel.setText(_translate("tabWidget", "Net Flowchart", None))
        tabWidget.setTabText(tabWidget.indexOf(self.configTab), _translate("tabWidget", "Configure", None))
        self.controlBox.setTitle(_translate("tabWidget", "Controls", None))
        self.trainButton.setText(_translate("tabWidget", "Train", None))
        self.stopButton.setText(_translate("tabWidget", "Stop", None))
        self.resumeButton.setText(_translate("tabWidget", "Resume", None))
        tabWidget.setTabText(tabWidget.indexOf(self.trainTab), _translate("tabWidget", "Train", None))
        self.parametersLabel_2.setText(_translate("tabWidget", "Parameters", None))
        self.netFlowchartLabel_2.setText(_translate("tabWidget", "Net Flowchart", None))
        self.displayLabel.setText(_translate("tabWidget", "Display", None))
        tabWidget.setTabText(tabWidget.indexOf(self.testTab), _translate("tabWidget", "Test", None))

from pyqtgraph.parametertree.ParameterTree import ParameterTree
from pyqtgraph import GraphicsLayoutWidget
from pyqtgraph.dockarea import DockArea
